version: '3.4'

services:
  accountinfoservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5100:80"

  addressservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5101:80"


  attendanceservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5102:80"


  gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5103:80"


  libraryservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5104:80"


  resultservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5105:80"

  jaeger:
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411